### ISSUE TITLE
Doesn't convert anything

### ISSUE THREAD

**Issue by ghost** [Vorono4ka/scw2dae#10]
Bug Description
**Absolutelly nothing happens whatever tool you select. The only thing it does - it closes the main.py file.**

I expected for this to work... but it didn't
I'm going to use Brawl Assets instead of this... sorry.

**Comment by danila-schelkov** [comment]
Send a traceback or any error so that I can find out the problem

**Comment by ghost** [comment]
The application does **not** send any tracebacks/errors. I guess you could make a debug thingy to better understand why is this hapenning? Also, if you want, I can help with fixing the issue. (Pretty good at Python)

**Comment by danila-schelkov** [comment]
There are no messages in the console? It's a little bit strange. Which version of python had you used?

**Comment by ghost** [comment]
I used Python 3.9.15
I have the latest version of pip, 3d-converter and other modules. But these ones that were required to use your script are installed. For sure. I also can give you system information if needed.

**Comment by ghost** [comment]
> There are no messages in the console? It's a little bit strange. Which version of python had you used?

Okay, it worked 😄

After re-installing Windows it worked and I have a good model of 8-bit. Nice app though. I improved it a tiny bit. I placed it in **Issues**. You'll find more info there :)
