### ISSUE TITLE
Some animations don't work

### ISSUE THREAD

**Issue by PhoenixFire6934** [Vorono4ka/scw2dae#4]
I've tried to convert more models with their animations and I noticed some animations do not play in Blender (the brawler stands with T pose).
Some examples:
-Barbarian King Bull
-Rogue Mortis
-brawlers a little bit old (like shelly, crow, carl, leon,spike etc)

Is this a known issue?

**Comment by danila-schelkov** [comment]
Yes, this problem is well known to me and I plan to get rid of it in the next update, thank you! Also a Big thank you for what you have described which models have these defects :)

**Comment by danila-schelkov** [comment]
If you will find such models, please write here a list of them and I would be grateful if you give me these "broken" files, thanks in advance

**Comment by 007Unknown** [comment]
8bit and virus 8bit also had some errors.
They did work to convert but their animation was bugged
[example here](https://cdn.discordapp.com/attachments/721792404629487647/723320793517523004/WXWg7QomJk.mp4)
Same happens with new pam model
If I find others I'll let you know

**Comment by Live-To-Live** [comment]
> 8bit and virus 8bit also had some errors.
> They did work to convert but their animation was bugged
> [example here](https://cdn.discordapp.com/attachments/721792404629487647/723320793517523004/WXWg7QomJk.mp4)
> Same happens with new pam model
> If I find others I'll let you know

Try to check all the boxes in the Importing section and then Import the file to Blender. Some Animations still won't work well, but it fixes the bones a little bit.
![Check](https://user-images.githubusercontent.com/66442806/88474847-38b6b080-cf33-11ea-8f91-fbd3dbef3aef.PNG)
