### ISSUE TITLE
Memory error while running scw2dae.py

### ISSUE THREAD

**Issue by SouravKB** [Vorono4ka/scw2dae#6]
I was trying to covert warriorprincess(I guess it refers to royal champion(coc)) scw file to dae file. I tried it multiple times, but every time I got memory error.

I am using windows 10 OS-64bit, with python 3.8 installed. My PC has 8GB RAM.

_here is the traceback of scw2dae.py_

Main file name: warriorprincess_default_anim_attack1.scw
Second file name (animation) (If you don't want the animation to be, leave the field blank and press Enter): 
Traceback (most recent call last):
  File "C:\Users\Sourav Kannantha B\Documents\Misc\scw2dae-master\scw2dae.py", line 383, in <module>
    ScwReader()
  File "C:\Users\Sourav Kannantha B\Documents\Misc\scw2dae-master\scw2dae.py", line 347, in __init__
    chunks.append(chunkreader.read(length))
MemoryError

**Comment by danila-schelkov** [comment]
Maybe you have Python x32? You need to install Python x64!

**Comment by danila-schelkov** [comment]
I think I need to close this issue  sorry
