### ISSUE TITLE
Not creating .dae but works with .obj

### ISSUE THREAD

**Issue by HexHyte** [Vorono4ka/scw2dae#7]
When selecting Tool 2 (scw2dae) the Python window closes.
When selecting Tool 1 (scw2obj) the script correctly create a .obj file with the proper 3D model.

![image](https://user-images.githubusercontent.com/37019481/104392387-3e846a80-5542-11eb-9890-1f7df9ea1d8a.png)

**Comment by danila-schelkov** [comment]
i think it's because you are using python 3.7. I'll fix it in the next update, thank yo so much

**Comment by HexHyte** [comment]
Installing last Python version (3.9) did the trick but i need to manually open the script (main.py) from Pyhton.exe (64bit) or the 32bit version will launch instead.

**Comment by Ygor888** [comment]
I have the same problem
